# MoerEngine Config
# C++ side definition in: source/runtime/core/include/config/GlobalConfig.h

[editor]
width = 1920
height = 1080
fullscreen = false
vsync = false

lock_frame_rate = false
fps = 60
max_fps = 170
font_size = 17.0

[engine]

[engine.rhi]
type = "Vulkan"
api_version = "1.3"

# type = "D3D12"

max_frame_in_flight = 3

[engine.render]
# default_render_method = "Raster"
default_render_method = "Raster"

[engine.render.raster]
enable_shadow = true

[engine.scene]
# 注：Toml中使用单引号包裹路径，可以避免反斜杠被识别为转义符
# 注：scene_path支持绝对路径
scene_path = './asset/scenes/sponza/Sponza.gltf'
enable_cache = true # 如果在开发SceneParser等功能，需要每次重新读取场景，那么可以关闭这个选项
material_info_log_lines = 20 # 加载场景时，打印材质信息的最大行数。-1 表示全部打印